services:
  api:
    build:
      context: ./
      dockerfile: ./docker/api/Dockerfile
    image: cje-i-2025-opac-api
    container_name: cje-i-2025-opac-api
    command: >
      sh -c "sh ./install.sh && exec tail -f /dev/null"
    tty: true
    working_dir: /app
    ports:
      - "8888:80"
    volumes:
      - ./cje1install.sh:/app/cje1install.sh
    develop:
      watch:
        - action: sync
          path: ./
          target: ./
          ignore:
            - ./.venv/
        - action: rebuild
          path: ./uv.lock
